In [ ]:
import pandas as pd

In [ ]:
 df = pd.read_csv("/content/customer_churn_dataset.csv")

In [ ]:
df.head()

   Age  Tenure  MonthlySpend  Churn
0   45       8          1487      0
1   27       1          1124      0
2   48       4           254      0
3   45       1          1866      0
4   29       8           999      0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           300 non-null    int64
 1   Tenure        300 non-null    int64
 2   MonthlySpend  300 non-null    int64
 3   Churn         300 non-null    int64
dtypes: int64(4)
memory usage: 9.5 KB

In [ ]:
df["Churn"].value_counts()

Churn
0    279
1     21
Name: count, dtype: int64

In [ ]:
# Import ML model
from sklearn.linear_model import LogisticRegression

In [ ]:
x = df[['Age', 'Tenure', 'MonthlySpend']]
y = df['Churn']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=42)

In [ ]:
model = LogisticRegression()
model.fit(x,y)

LogisticRegression()

In [ ]:
prediction = model.predict(x_test)
prediction

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [ ]:
df.tail()

     Age  Tenure  MonthlySpend  Churn
295   45       2          1004      0
296   46       6          1394      0
297   28       3          1135      0
298   45       4          1185      0
299   41       1           382      1

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
accuracy = model.score(x_test, y_test)

In [ ]:
accuracy_score(y_test,prediction)

0.9777777777777777

In [ ]:
confusion_matrix(y_test, prediction)

array([[85,  0],
       [ 2,  3]])