In [ ]:
import pandas as pd

In [ ]:
 df = pd.read_csv("/content/retail_store_sales_dataset.csv")

In [ ]:
df.shape

(220, 13)

In [ ]:
df["city"].value_counts()

city
Hyderabad    58
Bangalore    49
Chennai      40
Mysore       38
Pune         35
Name: count, dtype: int64

In [ ]:
df["product_category"]

0       Home Decor
1       Home Decor
2         Clothing
3       Home Decor
4           Beauty
          ...
215     Home Decor
216         Beauty
217    Electronics
218      Groceries
219     Home Decor
Name: product_category, Length: 220, dtype: object

In [ ]:
df.head(10)

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
0,5001,Pune,Central Mall,Home Decor,Face Cream,2386,4,Returning,Card,15,9544,1431.60,8112.40
1,5002,Bangalore,City Center,Home Decor,Wall Lamp,1383,1,New,Card,10,1383,138.30,1244.70
2,5003,Hyderabad,Central Mall,Clothing,Jeans,4937,1,Returning,UPI,5,4937,246.85,4690.15
3,5004,Hyderabad,Smart Bazaar,Home Decor,Mixer,1470,2,Returning,UPI,10,2940,294.00,2646.00
4,5005,Hyderabad,Central Mall,Beauty,Headphones,2688,1,New,Cash,10,2688,268.80,2419.20
5,5006,Mysore,Urban Retail,Electronics,Rice Bag,1652,4,Returning,UPI,0,6608,0.00,6608.00
6,5007,Hyderabad,Metro Mart,Home Decor,Wall Lamp,2739,2,New,Card,15,5478,821.70,4656.30
7,5008,Chennai,Central Mall,Electronics,Mixer,3899,3,New,Cash,15,11697,1754.55,9942.45
8,5009,Pune,Central Mall,Electronics,Wall Lamp,4628,3,Returning,UPI,10,13884,1388.40,12495.60
9,5010,Bangalore,City Center,Home Decor,Wall Lamp,2414,4,Returning,Card,5,9656,482.80,9173.20

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    220 non-null    int64
 1   city              220 non-null    object
 2   store             220 non-null    object
 3   product_category  220 non-null    object
 4   product_name      220 non-null    object
 5   unit_price        220 non-null    int64
 6   quantity          220 non-null    int64
 7   customer_type     220 non-null    object
 8   payment_method    220 non-null    object
 9   discount_percent  220 non-null    int64
 10  total_sale        220 non-null    int64
 11  discount_amount   220 non-null    float64
 12  final_amount      220 non-null    float64
dtypes: float64(2), int64(5), object(6)
memory usage: 22.5+ KB

In [ ]:
df["product_category"].value_counts().idxmax()

'Groceries'

In [ ]:
df.groupby("store")["transaction_id"].count().idxmax()

'Central Mall'

In [ ]:
df.groupby("city")["customer_type"].count().idxmax()

'Hyderabad'

In [ ]:
df["unit_price"].mean()

np.float64(2608.8681818181817)

In [ ]:
df["unit_price"].value_counts().idxmax()

np.int64(2414)

In [ ]:
df.groupby("city")["final_amount"].count().idxmax()

'Hyderabad'

In [ ]:
df["payment_method"].value_counts().idxmax()

'Card'

In [ ]:
df["customer_type"].value_counts().idxmax()

'Returning'

In [ ]:
df.groupby("product_category")["transaction_id"].count().idxmax()

'Groceries'

In [ ]:
df.groupby("store")["discount_amount"].count().idxmax()

'Central Mall'

In [ ]:
df.groupby("product_category")["quantity"].count().idxmax()

'Groceries'

In [ ]:
df.groupby("city")["final_amount"].count().idxmax()

'Hyderabad'

In [ ]:
df.groupby("product_category")["customer_type"].count().idxmax()

'Groceries'