In [ ]:
import pandas as pd

In [ ]:
 df = pd.read_csv("/content/swiggy_orders_dataset (2).csv")

In [ ]:
df.head()

,OrderValue,DeliveryDistance_km,RestaurantRating,PreparationTime_min,DeliveryTime_min
0,1010,3.87,5.0,26,41
1,1194,9.55,4.7,12,52
2,271,9.56,3.2,22,69
3,616,6.16,4.8,18,44
4,480,6.69,4.7,16,44

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OrderValue           400 non-null    int64
 1   DeliveryDistance_km  400 non-null    float64
 2   RestaurantRating     400 non-null    float64
 3   PreparationTime_min  400 non-null    int64
 4   DeliveryTime_min     400 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 15.8 KB

In [ ]:
df["DeliveryTime_min"].value_counts()

DeliveryTime_min
44    17
46    14
53    14
40    14
56    14
      ..
22     1
23     1
30     1
74     1
25     1
Name: count, Length: 63, dtype: int64

In [ ]:
# Import ML model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
x = df[['OrderValue', 'DeliveryDistance_km', 'RestaurantRating', 'PreparationTime_min']]
y = df['DeliveryTime_min']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [ ]:
prediction = model.predict(x_test)
prediction

array([62.45267435, 54.17918642, 51.9178255 , 41.64355587, 68.31141742,
       63.20928159, 31.58994531, 65.66942208, 44.0849096 , 78.62727843,
       57.62231212, 54.48651371, 45.83437447, 63.40058677, 52.75716955,
       38.27125909, 66.76065324, 49.03836426, 35.6666572 , 65.95600449,
       44.67354455, 55.88101777, 34.49362519, 33.28181943, 41.49624958,
       50.6702914 , 49.68012011, 38.13966213, 44.45790828, 40.157569  ,
       47.07264494, 44.78261105, 69.78241691, 77.29549161, 54.665733  ,
       41.43572606, 70.36012503, 54.59670646, 68.07541828, 48.22225838,
       52.11734576, 58.99164536, 38.19334034, 65.26508492, 31.56308395,
       39.75668279, 68.7532449 , 67.08810546, 67.74499701, 42.88380876,
       47.97054911, 74.34846113, 57.17517973, 55.20895562, 43.53866986,
       48.04795383, 53.15266543, 45.77497186, 46.11952099, 27.43025018,
       66.17793166, 45.3090614 , 33.0404061 , 71.23925969, 48.58331476,
       58.01957299, 36.45879411, 59.92983213, 60.28642805, 72.63278655,
       38.9258997 , 37.72967795, 49.22921527, 55.79267646, 41.57688865,
       55.74782302, 43.80125141, 64.61433812, 36.73651543, 39.82614295,
       43.67643744, 31.14352955, 54.14860494, 51.31293003, 54.00285619,
       78.09319226, 67.27492739, 65.46900666, 65.05285417, 62.14019737,
       31.33062513, 69.43989364, 26.5383558 , 69.18834792, 38.04896536,
       44.19535768, 40.94188411, 46.02458434, 70.0292355 , 56.46973421,
       53.10889086, 41.9321396 , 46.43267494, 38.66705388, 25.58194977,
       59.91794979, 39.74474652, 56.22139315, 36.55480695, 51.89349722,
       61.37714595, 62.88242845, 30.12328833, 73.12545069, 56.680996  ,
       41.00217332, 77.60007584, 50.99120275, 63.54065529, 43.83081883])

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test, prediction)

0.9995254269173952